"""
This type stub file was generated by pyright.
"""

"""
    tablib.core
    ~~~~~~~~~~~

    This module implements the central Tablib objects.

    :copyright: (c) 2016 by Kenneth Reitz. 2019 Jazzband.
    :license: MIT, see LICENSE for more details.
"""
__title__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
__docformat__ = ...
class Row:
    """Internal Row object. Mainly used for filtering."""
    __slots__ = ...
    def __init__(self, row=..., tags=...) -> None:
        ...
    
    def __iter__(self): # -> Generator[Any, None, None]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __getitem__(self, i):
        ...
    
    def __setitem__(self, i, value): # -> None:
        ...
    
    def __delitem__(self, i): # -> None:
        ...
    
    def __getstate__(self): # -> tuple[list[Any] | Any, list[Any] | Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    def rpush(self, value): # -> None:
        ...
    
    def lpush(self, value): # -> None:
        ...
    
    def append(self, value): # -> None:
        ...
    
    def insert(self, index, value): # -> None:
        ...
    
    def copy(self): # -> Row:
        ...
    
    def __contains__(self, item): # -> bool:
        ...
    
    @property
    def tuple(self): # -> tuple[Any, ...]:
        """Tuple representation of :class:`Row`."""
        ...
    
    @property
    def list(self): # -> list[Any]:
        """List representation of :class:`Row`."""
        ...
    
    def has_tag(self, tag): # -> bool:
        """Returns true if current row contains tag."""
        ...
    


class Dataset:
    """The :class:`Dataset` object is the heart of Tablib. It provides all core
    functionality.

    Usually you create a :class:`Dataset` instance in your main module, and append
    rows as you collect data. ::

        data = tablib.Dataset()
        data.headers = ('name', 'age')

        for (name, age) in some_collector():
            data.append((name, age))


    Setting columns is similar. The column data length must equal the
    current height of the data and headers must be set. ::

        data = tablib.Dataset()
        data.headers = ('first_name', 'last_name')

        data.append(('John', 'Adams'))
        data.append(('George', 'Washington'))

        data.append_col((90, 67), header='age')


    You can also set rows and headers upon instantiation. This is useful if
    dealing with dozens or hundreds of :class:`Dataset` objects. ::

        headers = ('first_name', 'last_name')
        data = [('John', 'Adams'), ('George', 'Washington')]

        data = tablib.Dataset(*data, headers=headers)

    :param \\*args: (optional) list of rows to populate Dataset
    :param headers: (optional) list strings for Dataset header row
    :param title: (optional) string to use as title of the Dataset


    .. admonition:: Format Attributes Definition

    If you look at the code, the various output/import formats are not
    defined within the :class:`Dataset` object. To add support for a new format, see
    :ref:`Adding New Formats <newformats>`.

    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __getitem__(self, key): # -> list[Any] | tuple[Any, ...]:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def __delitem__(self, key): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    headers = ...
    dict = ...
    @property
    def height(self): # -> int:
        """The number of rows currently in the :class:`Dataset`.
           Cannot be directly modified.
        """
        ...
    
    @property
    def width(self): # -> int:
        """The number of columns currently in the :class:`Dataset`.
           Cannot be directly modified.
        """
        ...
    
    def load(self, in_stream, format=..., **kwargs): # -> Self:
        """
        Import `in_stream` to the :class:`Dataset` object using the `format`.
        `in_stream` can be a file-like object, a string, or a bytestring.

        :param \\*\\*kwargs: (optional) custom configuration to the format `import_set`.
        """
        ...
    
    def export(self, format, **kwargs):
        """
        Export :class:`Dataset` object to `format`.

        :param \\*\\*kwargs: (optional) custom configuration to the format `export_set`.
        """
        ...
    
    def insert(self, index, row, tags=...): # -> None:
        """Inserts a row to the :class:`Dataset` at the given index.

        Rows inserted must be the correct size (height or width).

        The default behaviour is to insert the given row to the :class:`Dataset`
        object at the given index.

        You can add :ref:`tags <tags>` to the row you are inserting.
        This gives you the ability to :method:`filter <Dataset.filter>` your
        :class:`Dataset` later.
        """
        ...
    
    def rpush(self, row, tags=...): # -> None:
        """Adds a row to the end of the :class:`Dataset`.
        See :method:`Dataset.insert` for additional documentation.
        """
        ...
    
    def lpush(self, row, tags=...): # -> None:
        """Adds a row to the top of the :class:`Dataset`.
        See :method:`Dataset.insert` for additional documentation.
        """
        ...
    
    def append(self, row, tags=...): # -> None:
        """Adds a row to the :class:`Dataset`.
        See :method:`Dataset.insert` for additional documentation.
        """
        ...
    
    def extend(self, rows, tags=...): # -> None:
        """Adds a list of rows to the :class:`Dataset` using
        :method:`Dataset.append`
        """
        ...
    
    def lpop(self): # -> list[Any] | tuple[Any, ...]:
        """Removes and returns the first row of the :class:`Dataset`."""
        ...
    
    def rpop(self): # -> list[Any] | tuple[Any, ...]:
        """Removes and returns the last row of the :class:`Dataset`."""
        ...
    
    def pop(self): # -> list[Any] | tuple[Any, ...]:
        """Removes and returns the last row of the :class:`Dataset`."""
        ...
    
    def get(self, index): # -> list[Any] | tuple[Any, ...]:
        """Returns the row from the :class:`Dataset` at the given index."""
        ...
    
    def insert_col(self, index, col=..., header=...): # -> None:
        """Inserts a column to the :class:`Dataset` at the given index.

        Columns inserted must be the correct height.

        You can also insert a column of a single callable object, which will
        add a new column with the return values of the callable each as an
        item in the column. ::

            data.append_col(col=random.randint)

        If inserting a column, and :attr:`Dataset.headers` is set, the
        header attribute must be set, and will be considered the header for
        that row.

        See :ref:`dyncols` for an in-depth example.
        """
        ...
    
    def rpush_col(self, col, header=...): # -> None:
        """Adds a column to the end of the :class:`Dataset`.
        See :method:`Dataset.insert` for additional documentation.
        """
        ...
    
    def lpush_col(self, col, header=...): # -> None:
        """Adds a column to the top of the :class:`Dataset`.
        See :method:`Dataset.insert` for additional documentation.
        """
        ...
    
    def insert_separator(self, index, text=...): # -> None:
        """Adds a separator to :class:`Dataset` at given index."""
        ...
    
    def append_separator(self, text=...): # -> None:
        """Adds a :ref:`separator <separators>` to the :class:`Dataset`."""
        ...
    
    def append_col(self, col, header=...): # -> None:
        """Adds a column to the :class:`Dataset`.
        See :method:`Dataset.insert_col` for additional documentation.
        """
        ...
    
    def get_col(self, index): # -> list[Any]:
        """Returns the column from the :class:`Dataset` at the given index."""
        ...
    
    def add_formatter(self, col, handler): # -> Literal[True]:
        """Adds a formatter to the :class:`Dataset`.

        :param col: column to. Accepts index int, header str, or None to apply
                    the formatter to all columns.
        :param handler: reference to callback function to execute against
                        each cell value.
        """
        ...
    
    def filter(self, tag): # -> Self:
        """Returns a new instance of the :class:`Dataset`, excluding any rows
        that do not contain the given :ref:`tags <tags>`.
        """
        ...
    
    def sort(self, col, reverse=...): # -> Dataset:
        """Sort a :class:`Dataset` by a specific column, given string (for
        header) or integer (for column index). The order can be reversed by
        setting ``reverse`` to ``True``.

        Returns a new :class:`Dataset` instance where columns have been
        sorted.
        """
        ...
    
    def transpose(self): # -> Dataset | None:
        """Transpose a :class:`Dataset`, turning rows into columns and vice
        versa, returning a new ``Dataset`` instance. If the instance has
        headers, the first row of the original instance becomes the new header
        row."""
        ...
    
    def stack(self, other): # -> Self | None:
        """Stack two :class:`Dataset` instances together by
        joining at the row level, and return new combined
        ``Dataset`` instance."""
        ...
    
    def stack_cols(self, other): # -> Dataset | None:
        """Stack two :class:`Dataset` instances together by
        joining at the column level, and return a new
        combined ``Dataset`` instance. If either ``Dataset``
        has headers set, than the other must as well."""
        ...
    
    def remove_duplicates(self): # -> None:
        """Removes all duplicate rows from the :class:`Dataset` object
        while maintaining the original order."""
        ...
    
    def wipe(self): # -> None:
        """Removes all content and headers from the :class:`Dataset` object."""
        ...
    
    def subset(self, rows=..., cols=...): # -> Dataset | None:
        """Returns a new instance of the :class:`Dataset`,
        including only specified rows and columns.
        """
        ...
    


class Databook:
    """A book of :class:`Dataset` objects.
    """
    def __init__(self, sets=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def wipe(self): # -> None:
        """Removes all :class:`Dataset` objects from the :class:`Databook`."""
        ...
    
    def sheets(self): # -> list[Any]:
        ...
    
    def add_sheet(self, dataset): # -> None:
        """Adds given :class:`Dataset` to the :class:`Databook`."""
        ...
    
    @property
    def size(self): # -> int:
        """The number of the :class:`Dataset` objects within :class:`Databook`."""
        ...
    
    def load(self, in_stream, format, **kwargs): # -> Self:
        """
        Import `in_stream` to the :class:`Databook` object using the `format`.
        `in_stream` can be a file-like object, a string, or a bytestring.

        :param \\*\\*kwargs: (optional) custom configuration to the format `import_book`.
        """
        ...
    
    def export(self, format, **kwargs):
        """
        Export :class:`Databook` object to `format`.

        :param \\*\\*kwargs: (optional) custom configuration to the format `export_book`.
        """
        ...
    


def detect_format(stream): # -> None:
    """Return format name of given stream (file-like object, string, or bytestring)."""
    ...

def import_set(stream, format=..., **kwargs): # -> Dataset:
    """Return dataset of given stream (file-like object, string, or bytestring)."""
    ...

def import_book(stream, format=..., **kwargs): # -> Databook:
    """Return dataset of given stream (file-like object, string, or bytestring)."""
    ...

