"""
This type stub file was generated by pyright.
"""

def normalize_input(stream): # -> StringIO | BytesIO:
    """
    Accept either a str/bytes stream or a file-like object and always return a
    file-like object.
    """
    ...

