"""
This type stub file was generated by pyright.
"""

from functools import partialmethod
from importlib import import_module
from importlib.util import find_spec
from ..exceptions import UnsupportedFormat
from ..utils import normalize_input
from ._csv import CSVFormat
from ._json import JSONFormat
from ._tsv import TSVFormat

""" Tablib - formats
"""
uninstalled_format_messages = ...
def load_format_class(dotted_path): # -> Any:
    ...

class FormatDescriptorBase:
    def __init__(self, key, format_or_path) -> None:
        ...
    
    def ensure_format_loaded(self): # -> None:
        ...
    


class ImportExportBookDescriptor(FormatDescriptorBase):
    def __get__(self, obj, cls, **kwargs): # -> Any:
        ...
    
    def __set__(self, obj, val): # -> Any:
        ...
    


class ImportExportSetDescriptor(FormatDescriptorBase):
    def __get__(self, obj, cls, **kwargs): # -> Any:
        ...
    
    def __set__(self, obj, val): # -> Any:
        ...
    


class Registry:
    _formats = ...
    def register(self, key, format_or_path): # -> None:
        ...
    
    def register_builtins(self): # -> None:
        ...
    
    def formats(self): # -> Generator[Any, Any, None]:
        ...
    
    def get_format(self, key):
        ...
    


registry = ...
