"""
This type stub file was generated by pyright.
"""

""" Tablib - *SV Support.
"""
class CSVFormat:
    title = ...
    extensions = ...
    DEFAULT_DELIMITER = ...
    @classmethod
    def export_stream_set(cls, dataset, **kwargs): # -> StringIO:
        """Returns CSV representation of Dataset as file-like."""
        ...
    
    @classmethod
    def export_set(cls, dataset, **kwargs): # -> str:
        """Returns CSV representation of Dataset."""
        ...
    
    @classmethod
    def import_set(cls, dset, in_stream, headers=..., skip_lines=..., **kwargs): # -> None:
        """Returns dataset from CSV stream."""
        ...
    
    @classmethod
    def detect(cls, stream, delimiter=...): # -> bool:
        """Returns True if given stream is valid CSV."""
        ...
    


