"""
This type stub file was generated by pyright.
"""

""" Tablib - JSON Support
"""
def serialize_objects_handler(obj): # -> str:
    ...

class JSONFormat:
    title = ...
    extensions = ...
    @classmethod
    def export_set(cls, dataset): # -> str:
        """Returns JSON representation of Dataset."""
        ...
    
    @classmethod
    def export_book(cls, databook): # -> str:
        """Returns JSON representation of Databook."""
        ...
    
    @classmethod
    def import_set(cls, dset, in_stream): # -> None:
        """Returns dataset from JSON stream."""
        ...
    
    @classmethod
    def import_book(cls, dbook, in_stream): # -> None:
        """Returns databook from JSON stream."""
        ...
    
    @classmethod
    def detect(cls, stream): # -> bool:
        """Returns True if given stream is valid JSON."""
        ...
    


