"""
This type stub file was generated by pyright.
"""

from ._csv import CSVFormat

""" Tablib - TSV (Tab Separated Values) Support.
"""
class TSVFormat(CSVFormat):
    title = ...
    extensions = ...
    DEFAULT_DELIMITER = ...


