# Generated by Django 6.0.3 on 2026-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notice_type', models.CharField(choices=[('all', 'All Students'), ('level', 'Specific Level'), ('selected', 'Selected Students'), ('single', 'One Student')], max_length=20)),
                ('target_level', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_students', models.ManyToManyField(blank=True, to='students.student')),
            ],
        ),
    ]
